name: flutter_nice_widgets
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/unclemeric

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  azlistview: ^2.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  contacts_service: any
  dio: ^3.0.10
  image_picker: ^0.8.2
  flutter_datetime_picker: ^1.5.1
  # 汉字转拼音
  lpinyin: ^2.0.0
  shared_preferences: ^2.0.7
  package_info: ^2.0.2
  permission_handler: ^5.1.0+2
  webview_flutter: ^2.0.12
  flutter_app_upgrade: 
    git: https://github.com/unclemeric/flutter-app-upgrade.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
